### ISSUE TITLE
CSD2100

### ISSUE THREAD

**Issue by Chengrong98** [Jiamin88/Jiamin88#1]
Hi, can I check for the computer graphics mod taught by Prasanna, was there a final project after assignment 2?

**Comment by JeeJiaMin** [comment]
Hi,  yes there is a 3rd Assigment. Please refer to the following. 

Assignment #1: Line Rasterization, Triangle Rasterization, and Barycentric Interpolation

Assignment #2: Triangle Rasterization (depth interpolation, simple illumination model, shading, and texturing)

Assignment #3 - Final : 3D Pipeline (Culling, Clipping, and Rasterization)

# #
[final+project+specs.pdf](https://github.com/Jiamin88/Jiamin88/files/12142086/final%2Bproject%2Bspecs.pdf)
